### ISSUE TITLE
[Bug Report] Proxy value of new array item with default value is not usable in `onFieldInputValueChange` effect

### ISSUE THREAD

**Issue by ccpu** [alibaba/formily#2869]
- [x] I have searched the [issues](https://github.com/alibaba/formily/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formily-array-problem-15f970?file=/App.tsx:575-598)

### Steps to reproduce
1. go to  reproduction link provided
2. open console
3. click on add entry to add an item to array

### What is expected?
should be able to get pure object from proxy value when new item with default input value added to the array.

### What is actually happening?
Although the proxy value does have the expected data, when cloning or stringifying it returns an empty array of objects

### Package
@formily/antd@2.0.13

---

The array item has a default value:

```js
       <SchemaField.String
              default="foo"
              ...
```

As such, the `onFieldInputValueChange` method should reflect this value, which it does, but is not usable, because it can't be cloned or stringified.

Now wrapping the value in `setTimeout` will solve the problem:

```js
    onFieldInputValueChange("*", (field, form) => {
      setTimeout(() => {
        console.log("onFieldInputValueChange:", JSON.stringify(form.values));
      }, 0);
    });
```

What could be causing this?

**Comment by janryWang** [comment]
This is because the default attribute only takes effect when the component is rendered. When the add operation is triggered, it will be pushed first item, and the push will be completed before rendering. Therefore, there is a timing problem. Then, as a best practice, I recommend users to add components in the Addition component. configure default value

http://antd.formilyjs.org/components/array-table#arraytableaddition
